#ifndef RVM_SYSTEM_STATE_H
#define RVM_SYSTEM_STATE_H

typedef enum
{
    RVM_SYSTEM_STATE_BOOT = 0,
    RVM_SYSTEM_STATE_INIT,
    RVM_SYSTEM_STATE_READY,
    RVM_SYSTEM_STATE_STREAMING,
    RVM_SYSTEM_STATE_ERROR
} RVM_SystemState;

#endif /* RVM_SYSTEM_STATE_H */
