#ifndef RVM_NETWORK_STATE_H
#define RVM_NETWORK_STATE_H

typedef enum
{
    NETWORK_STATE_DISABLED = 0,
    NETWORK_STATE_INIT,
    NETWORK_STATE_CONNECTING,
    NETWORK_STATE_LOGIN,
    NETWORK_STATE_CONNECTED,
    NETWORK_STATE_BACKOFF
} NetworkState;

#endif /* RVM_NETWORK_STATE_H */
